language: python
python:
  - "3.7"
install:
  - pip install jupyter-client==6.1.6
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - black --target-version py37 --line-length 105 --check .
  - python -m pytest tests/*.py
  - pytest --cov-report term --cov=lux tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)